---
  title: "GAMs for Hirsutism data"
author: "Gregoire Gasparini, Aurora Hofman, Beatriu Tort"
date: "30 de marzo de 2020"
output: pdf_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hirsutism dataset

```{r}
hirs <- read.table("hirsutism.dat",header=T, sep="\t",fill=TRUE)
hirs$Treatment <- as.factor(hirs$Treatment)
summary(hirs)
boxplot(hirs[,2:5])
par(mfrow=c(2,2))
boxplot(hirs[,2]~Treatment,ylim=c(0,30), main=names(hirs)[2], xlab="Treatment")
boxplot(hirs[,3]~Treatment,ylim=c(0,30), main=names(hirs)[3], xlab="Treatment")
boxplot(hirs[,4]~Treatment,ylim=c(0,30), main=names(hirs)[4], xlab="Treatment")
boxplot(hirs[,5]~Treatment,ylim=c(0,30), main=names(hirs)[5], xlab="Treatment")
par(mfrow=c(1,1))
par(mfrow=c(2,2))
boxplot(hirs[Treatment==0,2:5],ylim=c(0,30), main="Treatment 0")
boxplot(hirs[Treatment==1,2:5],ylim=c(0,30), main="Treatment 1")
boxplot(hirs[Treatment==2,2:5],ylim=c(0,30), main="Treatment 2")
boxplot(hirs[Treatment==3,2:5],ylim=c(0,30), main="Treatment 3")
par(mfrow=c(1,1))
```

##Fit several GAM models (including semiparametric models) explaining $FGm12$ as a function of the variables that were measured at the beginning of the clinical trial (including $FGm0$) and $Treatment$ (treated as factor).

##1nd regression : linear model through gam (FGm12 ~ SysPres + FG0)

```{r}
library(mgcv)
attach(hirs)
am1.0 <- gam(FGm12 ~ SysPres + FGm0, data=hirs)
summary(am1.0)
#GCV score : 23.515 GCV score is the minimised generalised cross-validation (GCV) score of the GAM fitted.

```

##2rd regression : linear model through gam (FGm12 ~ SysPres + FG0)

```{r}
#S function : Function used in definition of smooth terms within gam model formulae. The function does not evaluate a (spline) smooth - it exists purely to help set up a model using spline based smooths.
library(mgcv)
attach(hirs)
as.factor(hirs$FGm0)
as.factor(hirs$FGm12)
am1.1 <- gam(FGm12 ~ s(FGm0)+s(SysPres), data=hirs)
plot(am1.1,pages=1,residuals=TRUE)
```




```{r}
library(rgl)
x <- seq(min(FGm0),max(FGm0), length= 30)
y <- seq(80,170, length= 30)
f <- function(x,y) { r <- predict(am1.1, newdata=data.frame(FGm0=x,SysPres=y))}
z <- outer(x, y, f)
open3d()
bg3d("white")
material3d(col="black")
persp3d(x, y, z, aspect=c(1, 1, 0.5), col = "lightblue",
xlab = "FGm0", ylab = "SysPres", zlab = "FGm12")
```

