---
---
title: "Local_poison_regression"
author: "Gregoire Gasparini, Aurora Hofman, Beatriu Tort"
date: "24 de marzo de 2020"
output: pdf_document
---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(splines)
```


```{r}
load("bikes.Washington.Rdata")
```

```{r}
cnt <- bikes$cnt
instant <- bikes$instant
```

```{r}
m<- smooth.spline(x= instant, y= cnt) #uses GCV by default. 
```

```{r}
#Penalty parameter:
m$lambda

#Correstponding degrees of freedom:
m$df

#Number of knots: 
length(m$fit$knot)


```

```{r}
df<- tibble(instant, cnt, m$x, m$y)

g<- ggplot(data = df, aes(instant, cnt)) + geom_point() + geom_line(aes(m$x, m$y), colour = "red")
g
```

```{r}
n.knots <- m$df - 4
my.knots <- quantile(instant, ((1:n.knots)-.5)/n.knots)

m_bs <- bs(instant, knots = my.knots)
m_lm <- lm(cnt~m_bs-1)

df_tot <- tibble(instant, cnt, m_lm$fitted.values, m$y)
g_lm <- ggplot(data = df_tot, aes(instant, cnt)) + geom_point(colour = "red", shape= 1) + geom_line(aes(instant, m_lm$fitted.values), color = "blue") + geom_line(aes(instant, m$y), colour = "green")
g_lm
```

















